#!/usr/bin/env node

const yargs = require("yargs")
const { hideBin } = require("yargs/helpers")

const { exec } = require("child_process")

const argv = yargs(hideBin(process.argv)).argv

if (argv.build || argv.B) {
    exec("pnpm run build", (err, stdout, stderr) => {
        if (err) {
            console.log(err)
            process.exit(1)
        }
        console.log("Done!\n")

        enter()
    })
    console.log("Building ix8r...")
} else {
    enter()
}

function enter() {
    let entryName = ""
    if (argv._.length >= 1) {
        entryName = argv._[0]
    } else if (typeof argv.build === "string") {
        entryName = argv.build
    } else if (typeof argv.B === "string") {
        entryName = argv.B
    }

    try {
        const entry = require("./dist/index")

        entry.default(entryName, argv)
    } catch(e) {
        console.log("Couldn't enter ix8r.")
        if (argv.debug || argv.D) {
            console.log(e)
        }
    }
}