#!/usr/bin/env node

const yargs = require("yargs")
const { hideBin } = require("yargs/helpers")

const { exec } = require("child_process")

const argv = yargs(hideBin(process.argv)).argv

if (argv.build || argv.B) {
    exec("pnpm run build", (err, stdout, stderr) => {
        if (err) {
            console.log(err)
            process.exit(1)
        }
        console.log("Done!\n")

        enter()
    })
    console.log("Building ix8r...")
} else {
    enter()
}

function enter() {
    if (argv._.length < 1) {
        console.log("Entry point not specified.")
        process.exit(1)
    }

    try {
        const entry = require("./dist/index")

        entry.default(argv._[0], argv)
    } catch(e) {
        console.log("Couldn't enter ix8r.")
    }
}